# Generated by Django 3.2.7 on 2021-10-05 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thehealth', '0002_alter_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MyClubUser',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
